name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_ng4SeHuDC4nb7tvX0cEgbetv2nMV/biglDR9iD8"
